name: Api Practice Yourself CD - Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_production:
    runs-on: self-hosted

    steps:
      - name: Run deployment sh
        shell: bash
        run: sh ${{ secrets.SH_PATH_PRODUCTION }}
