name: Api Practice Yourself CD - Test

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy_test:
    runs-on: self-hosted

    steps:
      - name: Run deployment sh
        shell: bash
        run: sh ${{ secrets.SH_PATH_TEST }}
