name: Api Practice Yourself CD - Test

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy_test:
    runs-on: self-hosted

    steps:
    - name: Pull code
      shell: bash
      run:
        echo ${{ secrets.SUDO_USER_PASSWORD }} | sudo -S git config --global --add safe.directory '*' && cd ${{ secrets.SERVER_TEST_DIR }} && git checkout dev && git pull && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist && php artisan migrate --force
    - name: Give Permission
      shell: bash
      run:
        echo ${{ secrets.SUDO_USER_PASSWORD }} | sudo -S chown www-data:www-data ${{ secrets.SERVER_TEST_DIR }}storage
        echo ${{ secrets.SUDO_USER_PASSWORD }} | sudo -S chmod -R 775 ${{ secrets.SERVER_TEST_DIR }}storage
        echo ${{ secrets.SUDO_USER_PASSWORD }} | sudo -S chown www-data:www-data ${{ secrets.SERVER_TEST_DIR }}bootstrap/cache
        echo ${{ secrets.SUDO_USER_PASSWORD }} | sudo -S chmod -R 775 ${{ secrets.SERVER_TEST_DIR }}bootstrap/cache
    # - name: Install update
    #   shell: bash
    #   run:
