name: Api Practice Yourself CD - Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_production:
    runs-on: self-hosted

    steps:
    - name: Change direction
      shell: bash
      run: cd ${{ secrets.SERVER_DIR }}
    - name: Setup git repo
      shell: bash
      run: 
        git checkout main
        git reset --hard
        git pull
    - name: Install update
      shell: bash
      run:
        chmod -R 775 storage
        chmod -R 775 bootstrap/cache
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        php artisan migrate
        
        
