name: Api Practice Yourself CD - Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_production:
    runs-on: self-hosted

    steps:
    - name: Change direction
      shell: bash
      run: cd ${{ secrets.SERVER_DIR }} && git branch && git checkout main && git pull && chmod -R 775 storage && chmod -R 775 bootstrap/cache && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist && php artisan migrate 
    # - name: Install update
    #   shell: bash
    #   run:
        
        
        
        
        
        
