name: Api Practice Yourself CD - Test

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy_test:
    runs-on: self-hosted

    steps:
    - name: Pull code
      shell: bash
      run: 
        cd ${{ secrets.SERVER_TEST_DIR }} && git checkout dev && git pull && chmod -R 775 storage && chmod -R 775 bootstrap/cache && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist && php artisan migrate --force
    # - name: Install update
    #   shell: bash
    #   run:
